version: '3'

networks:
  sv:
    driver: bridge

volumes:
  nexus-data:
  jenkins-data:
  jenkins-docker-certs:

services:
  nexus:
    image: sonatype/nexus3:latest
    restart: always
    ports:
      - "18081:8081"
      - "5000:5000"
    networks:
      - sv
    volumes:
      - nexus-data:/nexus-data      
  jenkins-docker:
    image: docker:dind
    privileged: true
    restart: always
    ports:
      - "2376:2376"
    networks:
      - sv
    volumes:
      - jenkins-data:/var/lib/jenkins/
      - jenkins-docker-certs:/certs/client
    environment:
      - DOCKER_TLS_CERTDIR=/certs
  jenkins:
    image: jenkinsci/blueocean:latest
    restart: always
    ports:
      - "18080:8080"
    networks:
      - sv
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/
      - jenkins-docker-certs:/certs/client:ro
    depends_on:
      - nexus
      - jenkins-docker
    environment:
      - NEXUS_PORT=8081
      - DOCKER_HOST=tcp://docker:2376
      - DOCKER_CERT_PATH=/certs/clien
      - DOCKER_TLS_VERIFY=1
      
  gitlab:
   image: gitlab/gitlab-ce:latest
   restart: always
   networks:
     - sv
   environment:
     GITLAB_OMNIBUS_CONFIG: |
       # external_url 'https://gitlab.example.com'
       # Add any other gitlab.rb configuration here, each on its own line
   ports:
     - "10080:80"
     - "10443:443"
     #- "10022:22"
   volumes:
     - /opt/gitlab/config:/etc/gitlab
     - /opt/gitlab/logs:/var/log/gitlab
     - /opt/gitlab/data:/var/opt/gitlab
